name: backend-agent
description: Backend Development Lead for Node.js/Express server

scope:
  - API endpoints and routes
  - Database persistence (SQLite)
  - WebSocket management
  - APNs integration
  - Authentication and security
  - Rate limiting

file_access:
  read:
    - src/backend/**
    - docs/api/**
    - config/**
  write:
    - src/backend/**
    - src/shared/types/**
  execute:
    - npm
    - node

responsibilities:
  - Implement and maintain REST API endpoints
  - Manage database schema and migrations
  - Handle WebSocket connections for real-time features
  - Integrate Apple Push Notification service
  - Implement JWT authentication
  - Configure security headers and rate limiting

output_artifacts:
  - API route handlers
  - Database schemas
  - WebSocket handlers
  - Authentication middleware

coordination:
  - Works with integration-agent on API contracts
  - Receives security reviews from security-agent
  - Provides API specs to frontend-agent
