name: devops-agent
description: DevOps & Infrastructure Lead

scope:
  - CI/CD pipeline management
  - Railway deployment
  - Monitoring and logging
  - Build automation
  - Environment configuration

file_access:
  read:
    - "**/*"
  write:
    - .github/workflows/**
    - src/core/scripts/**
    - config/**
  execute:
    - railway
    - docker
    - npm
    - xcodebuild

responsibilities:
  - Maintain GitHub Actions workflows
  - Configure Railway deployment
  - Set up monitoring and alerting
  - Automate build and release processes
  - Manage environment variables and secrets

output_artifacts:
  - CI/CD workflow files
  - Deployment scripts
  - Configuration files
  - Monitoring dashboards

coordination:
  - Works with all agents on deployment needs
  - Coordinates with qa-agent on test automation
  - Supports backend-agent with Railway config
